#!/bin/bash
echo get mariaDB image from docker hub...
sudo docker pull mariadb/server:10.3

echo run mariaDB image...
docker run -p 3308:3306  --name sfens-mariadb -e MARIADB_ROOT_PASSWORD=sfens-alian -d mariadb/server:tag
  
echo cd ...
cd S05P13A109/frontend/

echo build delete...
rm -rf  ./build

echo build...
npm run build

echo build...
docker build -t sfens-nginx .

echo run...
docker run -d --name sfens-nginx -p 80:80 sfens-nginx
